[build-system]
requires = [
	"pywin32; platform_system=='Windows'",
    "setuptools",
    "wxpython; platform_system=='Windows'",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = [
	".",
]
